# Generated by Django 5.2.5 on 2025-10-24 00:53

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='avatar',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='header/'),
        ),
        migrations.AlterField(
            model_name='header',
            name='background',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='header/'),
        ),
        migrations.AlterField(
            model_name='pdffile',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='main_image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='projects/main/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='projects/gallery/'),
        ),
    ]
